[deps]
cuda-nvcc = ">=12.1"
cudnn = ">=9.1,<10"
nccl = ">=2.18"
ipykernel = ""
numpy = "<2"
matplotlib = ""
python = "==3.11"
networkx = "==3.4"
graphviz = "==2.50"

[pip.deps]
brainpy = "==2.6.0"
brainpylib = "==0.3.1"
pathos = ""
jax = "==0.4.29"
jaxlib = "@https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.29+cuda12.cudnn91-cp311-cp311-manylinux2014_x86_64.whl"
taichi = "==1.7.0"