channels = ["nvidia", "anaconda"]

[deps]
cuda-nvcc = ">=12.1"
cudnn = ">=9.1,<10"
nccl = ">=2.18"
numpy = "<2"
python = "==3.12"
matplotlib = ""
networkx = "==3.4"
graphviz = "==2.50"

[pip.deps]
brainpy = "@git+https://github.com/brainpy/BrainPy@master"
jax = "==0.4.29"
jaxlib = "@https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.29+cuda12.cudnn91-cp312-cp312-manylinux2014_x86_64.whl"
pydot = "==3"
braintaichi = ""